// Copies the README of each project in BitMagic.Examples into the website, so
// the examples are documented in one place: the README is the source, and the
// page under Examples/ is generated from it.
//
// Run from a full superproject checkout (BitMagic.Examples and BitMagic.VSC
// must be siblings of BitMagic.Documentation), after `npm install` in
// tools/highlight: `node tools/examples/sync.mjs`.
//
// For every entry in `examples` below this writes:
//   - Examples/<Page>.md, the page itself (don't edit it, edit the README)
//   - Images/examples/<slug>/*, any images the README links to
//   - _data/examples.yml, which drives the Examples index page and the nav
// Re-run after changing a README, and commit the output.

import { readFile, writeFile, readdir, mkdir, rm, copyFile, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { createBmasmHighlighter, docsRoot } from "../highlight/highlighter.mjs";

const examplesRoot = path.resolve(docsRoot, "..", "BitMagic.Examples");
const examplesRepo = "https://github.com/Yazwh0/BitMagic.Examples";
const pagesDir = path.join(docsRoot, "Examples");
const imagesDir = path.join(docsRoot, "Images", "examples");
const dataFile = path.join(docsRoot, "_data", "examples.yml");
const marker = "<!-- Generated by tools/examples/sync.mjs";

// The order here is the order on the index page and in the nav.
// `repo` is set when the folder is a submodule, so links point at its own repo.
const examples = [
  {
    folder: "HelloWorld",
    slug: "hello-world",
    description: "An over engineered Hello World! Five different ways to print `HELLO WORLD!`, each using a different BitMagic feature.",
  },
  {
    folder: "DataGeneration",
    slug: "data-generation",
    description: "Uses C# to generate sine tables at compile time, then uses them to move a sprite around the screen.",
  },
  {
    folder: "NuGet",
    slug: "nuget",
    description: "References a NuGet package from a `.bmasm` file, using ImageSharp to convert an image to the X16 palette as part of the build.",
  },
  {
    folder: "FX/Cache",
    slug: "fx-cache",
    description: "How to use VERA's FX cache to copy VRAM four bytes at a time.",
  },
  {
    folder: "CommandLinePoc",
    slug: "command-line-poc",
    description: "A proof of concept for passing parameters to a machine code program from the BASIC prompt, demonstrated with a minimal `cat`.",
  },
  {
    folder: "Rom",
    slug: "rom",
    description: "How to write your own ROM code with BitMagic, and how to debug the official X16Community ROM.",
  },
  {
    folder: "Cc65Library",
    slug: "cc65-library",
    description: "Imports a library built with cc65 into a BitMagic project, using ZSMKit to play music.",
  },
  {
    folder: "Ca65Application",
    slug: "ca65-application",
    description: "A simple application written in ca65 and debugged in BitMagic using the `ld65` debug file.",
  },
  {
    folder: "Ca65DreamTracker",
    slug: "ca65-dream-tracker",
    description: "A much larger ca65 application: Tim Soderstrom's Dream Tracker, debugged in BitMagic.",
  },
  {
    folder: "BitBench",
    slug: "bitbench",
    repo: "https://github.com/Yazwh0/BitBench",
    description: "A proof of concept task switching and text based windowing system.",
  },
];

const imageExtensions = new Set([".png", ".gif", ".jpg", ".jpeg", ".webp", ".svg"]);

if (!existsSync(examplesRoot)) {
  console.error(
    `Can't find BitMagic.Examples at ${examplesRoot}.\n` +
      "This script needs BitMagic.Examples checked out as a sibling of BitMagic.Documentation " +
      "(clone the superproject with --recurse-submodules)."
  );
  process.exit(1);
}

const highlight = await createBmasmHighlighter();

// GitHub URL for a path inside an example, relative to the example's folder.
function sourceUrl(example, relPath, isDir) {
  const kind = isDir ? "tree" : "blob";
  if (example.repo) {
    return `${example.repo}/${kind}/main${relPath ? "/" + relPath : ""}`;
  }
  return `${examplesRepo}/${kind}/main/${example.folder}${relPath ? "/" + relPath : ""}`;
}

// The README's file name differs in case between examples; match it exactly
// so this works on case sensitive file systems too.
async function findReadme(dir) {
  const name = (await readdir(dir)).find((f) => f.toLowerCase() === "readme.md");
  return name ? path.join(dir, name) : null;
}

// Rewrites a link in an example's README so it works on the website.
async function rewriteLink(example, url, isImage, copiedImages) {
  // READMEs link to the site in full so the links work on GitHub too.
  const site = url.match(/^https?:\/\/(www\.)?bitmagic\.org(\/.*)?$/i);
  if (site) {
    return site[2] || "/";
  }

  if (/^([a-z]+:|#|\/)/i.test(url)) {
    return url;
  }

  const [target, anchor] = url.split("#");
  const exampleDir = path.posix.join(...example.folder.split("/"));
  const resolved = path.posix.normalize(path.posix.join(exampleDir, target)).replace(/\/$/, "");
  const fullPath = path.join(examplesRoot, ...resolved.split("/"));

  // A link to another example, or to its README, goes to that example's page.
  const linked = examples.find(
    (e) => resolved === e.folder || resolved.toLowerCase() === `${e.folder}/readme.md`.toLowerCase()
  );
  if (linked) {
    return `/examples/${linked.slug}${anchor ? "#" + anchor : ""}`;
  }

  if (!existsSync(fullPath)) {
    console.warn(`  ${example.folder}: link target '${url}' doesn't exist`);
  }

  if (isImage || imageExtensions.has(path.extname(resolved).toLowerCase())) {
    if (existsSync(fullPath)) {
      const name = path.basename(fullPath);
      const outDir = path.join(imagesDir, example.slug);
      await mkdir(outDir, { recursive: true });
      await copyFile(fullPath, path.join(outDir, name));
      copiedImages.push(name);
      return `/Images/examples/${example.slug}/${name}`;
    }
  }

  const relPath = path.posix.relative(exampleDir, resolved);
  const isDir = existsSync(fullPath) && (await stat(fullPath)).isDirectory();
  return sourceUrl(example, relPath, isDir) + (anchor ? "#" + anchor : "");
}

async function convert(example, markdown) {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const out = [];
  const copiedImages = [];
  let title = null;
  let fence = null; // { lang, lines } while inside a fenced code block

  for (const line of lines) {
    if (fence) {
      if (/^\s*```\s*$/.test(line)) {
        if (fence.lang === "bmasm" || fence.lang === "asm") {
          out.push(highlight(fence.lines.join("\n")));
        } else {
          out.push("```" + fence.lang, ...fence.lines, "```");
        }
        fence = null;
      } else {
        fence.lines.push(line);
      }
      continue;
    }

    const open = line.match(/^\s*```\s*(\S*)\s*$/);
    if (open) {
      fence = { lang: open[1].toLowerCase(), lines: [] };
      continue;
    }

    if (title === null) {
      const h1 = line.match(/^#\s+(.+?)\s*$/);
      if (h1) {
        title = h1[1];
      }
    }

    // Links and images: [text](url) and ![alt](url).
    const pattern = /(!?)\[([^\]]*)\]\(([^)\s]+)((?:\s+"[^"]*")?)\)/g;
    let rewritten = "";
    let last = 0;
    for (const m of line.matchAll(pattern)) {
      const url = await rewriteLink(example, m[3], m[1] === "!", copiedImages);
      rewritten += line.slice(last, m.index) + `${m[1]}[${m[2]}](${url}${m[4]})`;
      last = m.index + m[0].length;
    }
    out.push(rewritten + line.slice(last));
  }

  if (fence) {
    console.warn(`  ${example.folder}: unclosed code block`);
    out.push("```" + fence.lang, ...fence.lines, "```");
  }

  if (title === null) {
    console.warn(`  ${example.folder}: README has no '# ' heading, using the folder name`);
    title = example.folder;
  }

  return { title, body: out.join("\n").trim(), copiedImages };
}

const yamlString = (s) => JSON.stringify(s);

// Start from a clean slate, so a removed example or image doesn't linger.
await mkdir(pagesDir, { recursive: true });
for (const file of await readdir(pagesDir)) {
  const full = path.join(pagesDir, file);
  if (file.endsWith(".md") && (await readFile(full, "utf8")).includes(marker)) {
    await rm(full);
  }
}
await rm(imagesDir, { recursive: true, force: true });

const data = [];

for (const example of examples) {
  const dir = path.join(examplesRoot, ...example.folder.split("/"));
  const readme = existsSync(dir) ? await findReadme(dir) : null;
  if (!readme) {
    console.error(`${example.folder}: no README.md found, skipping`);
    continue;
  }

  const { title, body, copiedImages } = await convert(example, await readFile(readme, "utf8"));
  const url = `/examples/${example.slug}`;
  const source = sourceUrl(example, "", true);
  const readmePath = path.relative(path.resolve(docsRoot, ".."), readme).split(path.sep).join("/");

  // {% raw %} stops Liquid from treating anything in the README as a tag.
  const page = [
    "---",
    "layout: page",
    `title: ${yamlString(title)}`,
    `permalink: ${url}`,
    `description: ${yamlString(example.description.replace(/`/g, ""))}`,
    // The first image in the README is the page's preview when it's shared,
    // instead of the site-wide default.
    ...(copiedImages.length ? [`image: /Images/examples/${example.slug}/${copiedImages[0]}`] : []),
    "---",
    `${marker} from ${readmePath}. Edit the README, not this file. -->`,
    "{% raw %}",
    body,
    "",
    `[View the source on GitHub](${source})`,
    "{% endraw %}",
    "",
  ].join("\n");

  const pageName = example.folder.replace(/\//g, "") + ".md";
  await writeFile(path.join(pagesDir, pageName), page, "utf8");

  data.push({ title, url, description: example.description, source });

  const images = copiedImages.length ? `, ${copiedImages.length} image(s)` : "";
  console.log(`${readmePath} -> Examples/${pageName}${images}`);
}

const yaml =
  "# Generated by tools/examples/sync.mjs. Don't edit, re-run the script.\n\n" +
  data
    .map((d) =>
      [
        `- title: ${yamlString(d.title)}`,
        `  url: ${d.url}`,
        `  description: ${yamlString(d.description)}`,
        `  source: ${d.source}`,
      ].join("\n")
    )
    .join("\n\n") +
  "\n";
await writeFile(dataFile, yaml, "utf8");
console.log(`${data.length} examples -> _data/examples.yml`);

process.exit(0);
